---
language: python
branches:
  only:
    - master
#TODO: this script could be pulled dynamically
install:
  - pip install -U pip
script:
  # This installs dependencies, which installs tox, sphinx, twine
  - pip install -e .
  - python setup.py pkdeploy
